### ISSUE TITLE
EventsManager No Compilable

### ISSUE THREAD

**Issue by AndyIbanez** [UPBLPZ/UPB-Match#2]
Por alguna razón, EventsManager me aparece marcado rojo. Creo que sería mejor copiar y pegar la declaración de los métodos tal cual aparecen en el Interface.

Otra cosinga: Creo que @Override no es necesario en este caso ya que estamos sobreescribiendo el método de la interface, pero eso solo es un detalle pedante :P.

**Comment by AndyIbanez** [comment]
Ok, ya me di cuenta que no compila porque en el EventsManager, getEvents no tiene la palabra `final`. Una vez que le pongas eso debería compilar sin problemas.

**Comment by mickyfrade** [comment]
Solved :)
